version: '3.1'

services:

  postgres:
    image: postgres
    hostname: postgres
    restart: unless-stopped
    ports:
      - 5455:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: pass